name: main
on:
  push:
    paths:
      - '.github/workflows/*.yml'
      - 'solvers/**'
      - 'tutorials/**'
      - '!tutorials/resources/**'
  pull_request:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        foam: [openfoam8]
        case: [shockTube, tubePurging, pipeCompression, cylCyclic2D]
    steps:
    - uses: actions/checkout@v2
    - name: apt-get
      run: |
        sudo sh -c "wget -O - http://dl.openfoam.org/gpg.key | apt-key add -"
        sudo add-apt-repository "http://dl.openfoam.org/ubuntu dev"
        sudo add-apt-repository http://dl.openfoam.org/ubuntu
        sudo apt update
        sudo apt install -y ${{ matrix.foam }}
    - name: pip3
      run: pip3 install -r requirements.txt
      working-directory: src/foam2pandas

    - name: Allwmake
      run: . /opt/${{ matrix.foam }}/etc/bashrc && solvers/./Allwmake
    - name: Allrun
      run: |
        for CASE_PATH in *Foam/${{ matrix.case }}; do
          if test -d "$CASE_PATH"; then
            . /opt/${{ matrix.foam }}/etc/bashrc && $CASE_PATH/./Allrun
          fi
        done
      working-directory: tutorials
    - uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: ${{ matrix.foam }}, ${{ matrix.case }}
        path: tutorials/*Foam/${{ matrix.case }}/log.*

    - name: post_process.py
      run: ./post_process.py
      working-directory: tutorials/multiCompressionFoam/${{ matrix.case }}
    - uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.foam }}, ${{ matrix.case }}
        path: tutorials/multiCompressionFoam/${{ matrix.case }}/log.postProcess