name: pipeCompression
on:
  push:
    paths:
      - 'solvers/**'
      - 'tutorials/*Foam/pipeCompression/**'
  pull_request:
    branches:
      - master

jobs:
  pipeCompression:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: apt-get
      run: |
        sudo sh -c "wget -O - http://dl.openfoam.org/gpg.key | apt-key add -"
        sudo add-apt-repository "http://dl.openfoam.org/ubuntu dev"
        sudo apt update
        sudo apt install -y openfoam-dev
    - name: pip3
      run: pip3 install -r requirements.txt
      working-directory: src/foam2py

    - name: Allwmake
      run: . /opt/openfoam-dev/etc/bashrc && solvers/./Allwmake
    - name: Allrun
      run: |
        for CASE_PATH in *Foam/pipeCompression; do
          if test -d "$CASE_PATH"; then
            . /opt/openfoam-dev/etc/bashrc && $CASE_PATH/./Allrun
          fi
        done
      working-directory: tutorials
    - name: post_process.py
      run: ./post_process.py
      working-directory: tutorials/multiCompressionFoam/pipeCompression

    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: artifacts-pipeCompression
        path: |
          tutorials/*Foam/pipeCompression/log.*Mesh
          tutorials/*Foam/pipeCompression/log.*Foam