name: shockTube cases
on:
  push:
    paths:
      - 'solvers/**'
      - 'tutorials/*Foam/shockTube/**'
  pull_request:
    branches:
      - master

jobs:
  shockTubes:
    runs-on: ubuntu-latest
    steps:
    - name: Install OpenFOAM-dev
      run: |
        sudo sh -c "wget -O - http://dl.openfoam.org/gpg.key | apt-key add -"
        sudo add-apt-repository "http://dl.openfoam.org/ubuntu dev"
        sudo apt update
        sudo apt install -y openfoam-dev

    - uses: actions/checkout@v2
    - name: Compile solvers
      run: . /opt/openfoam-dev/etc/bashrc && solvers/./Allwmake

    - name: Run cases
      run: |
        for CASE in *Foam/shockTube; do
          . /opt/openfoam-dev/etc/bashrc && $CASE/./Allrun
        done
      working-directory: tutorials

    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: artifacts
        path: |
          tutorials/*Foam/shockTube/log.*(Mesh|Foam)
          tutorials/*Foam/shockTube/postProcessing/*.png
