name: shockTubes
on:
  push:
    paths:
      - 'solvers/**'
      - 'tutorials/**' # 'tutorials/*Foam/shockTube/**'
  pull_request:
    branches:
      - master

jobs:
  shockTubes:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: apt-get
      run: |
        sudo sh -c "wget -O - http://dl.openfoam.org/gpg.key | apt-key add -"
        sudo add-apt-repository "http://dl.openfoam.org/ubuntu dev"
        sudo apt update
        sudo apt install -y openfoam-dev
    - name: pip3
      run: pip3 install -r requirements.txt
      working-directory: src/foam2py

    - name: Allwmake
      run: . /opt/openfoam-dev/etc/bashrc && solvers/./Allwmake
    - name: Allrun
      run: |
        for CASE in *Foam/shockTube; do
          . /opt/openfoam-dev/etc/bashrc && $CASE/./Allrun
        done
      working-directory: tutorials
    - name: post_process.py
      run: ./post_process.py
      working-directory: tutorials/multiCompressionFoam/shockTube

    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: artifacts
        path: |
          tutorials/*Foam/shockTube/log.*Mesh
          tutorials/*Foam/shockTube/log.*Foam
          tutorials/*Foam/shockTube/postProcessing/*.png